INSERT INTO immediate_action (
    action_id,
    species_id,
    category_id,
    step_order,
    action_kind,
    action_text_en,
    action_text_ms,
    source_person,
    source_institution,
    source_url,
    date_verified
)
VALUES
(
    34,
    NULL,
    3,
    6,
    'do',
    'If bitten, immobilise the bitten limb and keep the whole body as still as possible while getting to hospital.',
    'Jika dipatuk, lumpuhkan pergerakan anggota badan yang dipatuk dan kekalkan seluruh badan setenang mungkin semasa dibawa ke hospital.',
    'Ahmad Khaldun Ismail',
    'Consultant Emergency Physician; Founding Advisor, Remote Envenomation Consultation Services (RECS), Universiti Kebangsaan Malaysia',
    'https://www.researchgate.net/publication/261712651_Remote_Envenomation_Consultation_Services_Recs_for_Healthcare_Providers_In_Malaysia',
    '2026-09-14'
),
(
    35,
    NULL,
    3,
    7,
    'do',
    'Remove rings, watches, bracelets and tight clothing near the bite before swelling starts.',
    'Tanggalkan cincin, jam tangan, gelang dan pakaian ketat berhampiran kesan gigitan sebelum bengkak berlaku.',
    'Dr Abdul Rahman Abdul Kadir',
    'The Malaysian Medical Gazette',
    'https://www.mmgazette.com/what-you-need-to-know-about-snake-bites-dr-abdul-rahman-abdul-kadir/',
    '2026-09-14'
),
(
    36,
    NULL,
    3,
    8,
    'do_not',
    'Do not tie anything around the bite or apply a tourniquet. It does not slow the venom and can damage the limb.',
    'Jangan ikat atau pasang tourniquet pada anggota badan yang dipatuk. Ia tidak melambatkan penyebaran bisa dan boleh merosakkan anggota badan.',
    'Dr Abdul Rahman Abdul Kadir',
    'The Malaysian Medical Gazette',
    'https://www.mmgazette.com/what-you-need-to-know-about-snake-bites-dr-abdul-rahman-abdul-kadir/',
    '2026-09-14'
),
(
    37,
    NULL,
    3,
    9,
    'do',
    'Wash the bite area with clean water only. Do not scrub or rub the wound.',
    'Basuh kawasan gigitan dengan air bersih sahaja. Jangan gosok atau lecek luka itu.',
    'Dr Abdul Rahman Abdul Kadir',
    'The Malaysian Medical Gazette',
    'https://www.mmgazette.com/what-you-need-to-know-about-snake-bites-dr-abdul-rahman-abdul-kadir/',
    '2026-09-14'
),
(
    38,
    NULL,
    3,
    10,
    'do',
    'Stay calm and confirm exactly where the snake is hiding before doing anything else.',
    'Kekal tenang dan pastikan dengan tepat di mana ular itu bersembunyi sebelum melakukan apa-apa tindakan lain.',
    NULL,
    'Department of Wildlife and National Parks Peninsular Malaysia (PERHILITAN), as relayed by iProperty.com.my',
    'https://www.iproperty.com.my/guides/what-to-do-when-wildlife-invades-your-home-77536',
    '2026-09-14'
),
(
    39,
    NULL,
    3,
    11,
    'do',
    'Note the snake''s physical details -- size, colour and pattern -- to help responders identify it.',
    'Catatkan ciri-ciri fizikal ular itu -- saiz, warna dan corak -- untuk membantu pihak bertugas mengenal pastinya.',
    NULL,
    'Department of Wildlife and National Parks Peninsular Malaysia (PERHILITAN), as relayed by iProperty.com.my',
    'https://www.iproperty.com.my/guides/what-to-do-when-wildlife-invades-your-home-77536',
    '2026-09-14'
),
(
    40,
    NULL,
    3,
    12,
    'do',
    'If it is safe to do so, keep the snake in sight from a safe distance without approaching it. This helps responders locate it faster.',
    'Jika selamat untuk berbuat demikian, kekalkan ular itu dalam pandangan dari jarak yang selamat tanpa menghampirinya. Ini membantu pihak bertugas mengesannya dengan lebih pantas.',
    NULL,
    'Department of Wildlife and National Parks Peninsular Malaysia (PERHILITAN), as relayed by iProperty.com.my',
    'https://www.iproperty.com.my/guides/what-to-do-when-wildlife-invades-your-home-77536',
    '2026-09-14'
);