DROP TABLE IF EXISTS immediate_action CASCADE;
DROP TABLE IF EXISTS species_behaviour CASCADE;
DROP TABLE IF EXISTS prevention_action CASCADE;
DROP TABLE IF EXISTS species_media CASCADE;
DROP TABLE IF EXISTS authority CASCADE;
DROP TABLE IF EXISTS species CASCADE;
DROP TABLE IF EXISTS animal_category CASCADE;
DROP TABLE IF EXISTS state CASCADE;