-- Iteration 2: normalize the wildlife complaint aggregate table used by /api/i2/complaints.
-- Semantics:
--   * one row = one state/species/year aggregate
--   * cases = number of complaints represented by that row
--   * species_id IS NULL = authoritative total complaints for the whole state/year
-- This table is NOT an event log; never count rows to derive complaint totals.

CREATE TABLE IF NOT EXISTS complaint_series (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    species_id INTEGER NULL,
    state_code INTEGER NOT NULL,
    year INTEGER NOT NULL,
    cases INTEGER NOT NULL,
    source_url TEXT,
    date_verified DATE,
    CONSTRAINT complaint_series_species_fk
        FOREIGN KEY (species_id) REFERENCES species(species_id),
    CONSTRAINT complaint_series_state_fk
        FOREIGN KEY (state_code) REFERENCES state(state_code),
    CONSTRAINT complaint_series_year_ck CHECK (year BETWEEN 1900 AND 2100),
    CONSTRAINT complaint_series_cases_ck CHECK (cases >= 0)
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'complaint_series_species_fk') THEN
        ALTER TABLE complaint_series
            ADD CONSTRAINT complaint_series_species_fk
            FOREIGN KEY (species_id) REFERENCES species(species_id) NOT VALID;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'complaint_series_state_fk') THEN
        ALTER TABLE complaint_series
            ADD CONSTRAINT complaint_series_state_fk
            FOREIGN KEY (state_code) REFERENCES state(state_code) NOT VALID;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'complaint_series_year_ck') THEN
        ALTER TABLE complaint_series
            ADD CONSTRAINT complaint_series_year_ck CHECK (year BETWEEN 1900 AND 2100) NOT VALID;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'complaint_series_cases_ck') THEN
        ALTER TABLE complaint_series
            ADD CONSTRAINT complaint_series_cases_ck CHECK (cases >= 0) NOT VALID;
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uq_complaint_series_species_year
    ON complaint_series (state_code, species_id, year)
    WHERE species_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_complaint_series_state_total_year
    ON complaint_series (state_code, year)
    WHERE species_id IS NULL;

CREATE INDEX IF NOT EXISTS ix_complaint_series_state_year
    ON complaint_series (state_code, year DESC);

CREATE INDEX IF NOT EXISTS ix_complaint_series_species_year
    ON complaint_series (species_id, year DESC)
    WHERE species_id IS NOT NULL;

COMMENT ON TABLE complaint_series IS
    'Aggregated wildlife complaint counts by state/species/year. species_id NULL stores the state total for the year.';
COMMENT ON COLUMN complaint_series.cases IS
    'Complaint count represented by this aggregate row; do not infer counts from row cardinality.';
COMMENT ON COLUMN complaint_series.species_id IS
    'Species foreign key. NULL means the aggregate total for all wildlife complaints in that state/year.';
